### PR TITLE
Add snowflake connector

### PR DESCRIPTION
**Pull request by danpi**
### Motivation

We will add the new Snowflake connector.

### Modifications

Add the Snowflake connector info to the connectors.yaml.

### Verifying this change

- [x] Make sure that the change passes the CI checks.

*(Please pick either of the following options)*

This change is a trivial rework / code cleanup without any test coverage.

*(or)*

This change is already covered by existing tests, such as *(please describe tests)*.

*(or)*

This change added tests and can be verified as follows:

*(example:)*
  - *Added integration tests for end-to-end deployment with large payloads (10MB)*
  - *Extended integration test for recovery after broker failure*

### Documentation

Check the box below.

Need to update docs? 

- [ ] `doc-required` 
  
  (If you need help on updating docs, create a doc issue)
  
- [x] `no-need-doc` 
  
  (Please explain why)
  
- [ ] `doc` 
  
  (If this PR contains doc changes)

### CODE REVIEW

**Comment by ericsyh** [comment]
@tuteng @urfreespace Do you Cloud Console's PR supports snowflake connector? We should cherry-pick SN Private Console.

**Review by maxsxu — APPROVED** [review]

**Review by urfreespace — APPROVED** [review]

**Comment by urfreespace** [comment]
> @tuteng @urfreespace Do you Cloud Console's PR supports snowflake connector? We should cherry-pick SN Private Console.

Just need Pulsar side support, the sinks and sources list data is API response from the pulsar side directly. @ericsyh

**Review by ericsyh — DISMISSED** [review]

**Comment by urfreespace** [comment]
https://pulsar.apache.org/sink-rest-api/?version=master#operation/getSinkList @ericsyh

**Review by maxsxu — APPROVED** [review]

**Comment by ericsyh** [comment]
@danpi Can you help update the image version to include https://github.com/streamnative/pulsar-io-snowflake/issues/50?

**Review by ericsyh — APPROVED** [review]
LGTM

**Pull request merged**
