### PR TITLE
BREAKING CHANGE(sn-platform): update zk reconfig

### LINKED ISSUE #867: [Private Cloud] replace `zookeeper.reconfig.zkServers` by `zookeeper.advanced.staticServerList`

### PR DESCRIPTION
**Pull request by ericsyh**
Signed-off-by: ericsyh <ericshenyuhao@outlook.com>

*(If this PR fixes a github issue, please add `Fixes #<xyz>`.)*

Fixes #867 

*(or if this PR is one task of a github issue, please add `Master Issue: #<xyz>` to link to the master issue.)*

Master Issue: #<xyz>

### Motivation

`.Values.zookeeper.reconfig.zkServers` is the legacy config from `streamnative/pulsar` chart. We should migrate the config with `.Values.zookeeper.reconfig.staticServerList`

### Modifications

1. Migrate `.Values.zookeeper.reconfig.zkServers` to `.Values.zookeeper.reconfig.staticServerList`
2. Remove legacy config `.Values.zookeeper.reconfig.zkServers`

### Verifying this change

- [x] Make sure that the change passes the CI checks.

*(Please pick either of the following options)*

This change is a trivial rework / code cleanup without any test coverage.

*(or)*

This change is already covered by existing tests, such as *(please describe tests)*.

*(or)*

This change added tests and can be verified as follows:

*(example:)*
  - *Added integration tests for end-to-end deployment with large payloads (10MB)*
  - *Extended integration test for recovery after broker failure*

### Documentation

Check the box below.

Need to update docs? 

- [ ] `doc-required` 
  
  (If you need help on updating docs, create a doc issue)
  
- [x] `no-need-doc` 
  
  (Please explain why)
  
- [ ] `doc` 
  
  (If this PR contains doc changes)

### CODE REVIEW

**Review by maxsxu — APPROVED** [review]
I think we should mark this PR as `need-doc`

**Comment by ericsyh** [comment]
> I think we should mark this PR as `doc-required `

1.8 has several BREAK CHANGE PRs. I will create a separate upgrade-guide doc to guide how to upgrade from previous versions. 
And yes. ZK reconfig has no doc now. Should add a one.

**Comment by fantapsody** [comment]
Reconfig might not be that advanced and we may consider enabling it by default in the future.

**Comment by ericsyh** [comment]
> Reconfig might not be that advanced and we may consider enabling it by default in the future.

Then shall we use `.Values.zookeeper.reconfig.enabled` and `.Values.zookeeper.reconfig.staticServerList`? Putting them under advanced just to keep consistent with the ZK CR config location.

**Comment by ericsyh** [comment]
@fantapsody PTAL

**Review by fantapsody — APPROVED** [review]

**Pull request merged**
