### PR TITLE
Add pulsar detector to repo

### PR DESCRIPTION
**Pull request by wolfstudy**
Signed-off-by: xiaolong.ran <rxl@apache.org>

- Add pulsar detector to repo

image

### CODE REVIEW

**Comment by wolfstudy** [comment]
image

**Comment by wolfstudy** [comment]
Verified in helm, everything is ok

**Comment by sijie** [comment]
@wolfstudy maybe make it a different chart. it doesn't have to be deployed with the main pulsar chart.

**Comment by wolfstudy** [comment]
> @wolfstudy maybe make it a different chart. it doesn't have to be deployed with the main pulsar chart.

The pulsar-detector needs to rely on the broker environment. Its main job is to detect the status of the broker. If it is deployed as a separate helm chart, how do we detect the status of the real broker we want to test?

**Comment by sijie** [comment]
>  If it is deployed as a separate helm chart, how do we detect the status of the real broker we want to test?

You can specify the pulsar cluster that you want to detect. But I am fine with us starting from this approach. We can change it in the future.

**Pull request merged**
