### PR TITLE
Allow setting nodeSelector and tolerations for pulsar-detector pod.

### LINKED ISSUE #473: [sn-platform] No `nodeSelector` and `tolerations` available for pulsar_detector
`nodeSelector` and `tolerations` are available as attributes for most of the services in the sn-platform chart. But there are no such attributes in `pulsar_detector` component. 

A similar issue might exist in the `pulsar` chart as well.

### PR DESCRIPTION
**Pull request by MarvinCai**
close #473

### CODE REVIEW

**Review by sijie — COMMENTED** [review]
Overall looks good to me. Can you add these two fields to the values file? Just like what we did for the other components?

**Review by sijie — APPROVED** [review]

**Review by fantapsody — APPROVED** [review]

**Comment by sijie** [comment]
@MarvinCai Can you fix the CI and merge it?

**Comment by MarvinCai** [comment]
the ci failure should have nothing to do with changes in this pr, I'll fix it in separate issue, merging it.

**Comment by sijie** [comment]
Add `doc-required` as we need to add documentation on how to use `nodeSelector` and `tolerations`.

**Pull request merged**
