### PR TITLE
Remove manifests that deploy Pulsar cluster using pure k8s resources.

### LINKED ISSUE #493: Remove code that deploys pulsar clusters using pure k8s manifests in sn-platform

### PR DESCRIPTION
**Pull request by MarvinCai**
resolves #493

### Motivation
Simply SN-Platform chart by unifying how to deploy Pulsar cluster

### Modifications
Remove manifests that deploy Pulsar cluster using pure k8s resources.

### Verifying this change
- [x] Make sure that the change passes the CI checks.

This change is a trivial rework / code cleanup without any test coverage.

### Documentation

Check the box below.

Need to update docs? 

- [x] `no-need-doc`

### CODE REVIEW

**Review by tuteng — APPROVED** [review]
Tried to install the cluster and it all seems to work

**Comment by maxsxu** [comment]
Does this mean users don't need to execute `helm install pulsar-operator streamnative/pulsar-operator` before installing a SNP anymore?

**Review by maxsxu — APPROVED** [review]
LGTM

**Review by ericsyh — APPROVED** [review]
LGTM

**Pull request merged**
