### PR TITLE
Support ImagePullSecrets in pulsar components

### PR DESCRIPTION
**Pull request by maxsxu**
### Motivation

Able to configure SN Platform to use a private registry.

### Modifications

- New feature values `global.imagePullSecret` in `charts/sn-platform`

- New CRDs that support imagePullSecrets in `charts/pulsar-operator`

### Verifying this change

- [x] Make sure that the change passes the CI checks.

*(Please pick either of the following options)*

This change is a trivial rework / code cleanup without any test coverage.

*(or)*

This change is already covered by existing tests, such as *(please describe tests)*.

*(or)*

This change added tests and can be verified as follows:

*(example:)*
  - *Added integration tests for end-to-end deployment with large payloads (10MB)*
  - *Extended integration test for recovery after broker failure*

### Documentation

Check the box below.

Need to update docs? 

- [x] `doc-required` 
  
  (If you need help on updating docs, create a doc issue)
  
- [ ] `no-need-doc` 
  
  (Please explain why)
  
- [ ] `doc` 
  
  (If this PR contains doc changes)

### Example values to enable imagePullSecrets
Just like the native K8s way

```
global:
    imagePullSecrets:
      - name: ghcr-secret
```

### CODE REVIEW

**Review by fantapsody — COMMENTED** [review]
LGTM. I wonder if it's common to use different image pull secrets for different components, or usually people just use the same image pull secrets for all components? Maybe like https://github.com/prometheus-community/helm-charts/blob/main/charts/kube-prometheus-stack/values.yaml#L118

**Comment by MarvinCai** [comment]
> LGTM. I wonder if it's common to use different image pull secrets for different components, or usually people just use the same image pull secrets for all components? Maybe like https://github.com/prometheus-community/helm-charts/blob/main/charts/kube-prometheus-stack/values.yaml#L118

+1, I think user usually just have a single private registry, so just a `imagePullSecrets` should be enough?

**Comment by fantapsody** [comment]
> > LGTM. I wonder if it's common to use different image pull secrets for different components, or usually people just use the same image pull secrets for all components? Maybe like https://github.com/prometheus-community/helm-charts/blob/main/charts/kube-prometheus-stack/values.yaml#L118
> 
> +1, I think user usually just have a single private registry, so just a `imagePullSecrets` should be enough?

@MarvinCai do you think we should use `global` for values like this to share them across subcharts?

**Comment by maxsxu** [comment]
> LGTM. I wonder if it's common to use different image pull secrets for different components, or usually people just use the same image pull secrets for all components? Maybe like https://github.com/prometheus-community/helm-charts/blob/main/charts/kube-prometheus-stack/values.yaml#L118

Agree with just one `imagePullSecrets` by setting a global value, as `imagePullSecrets` is an array which can contain multiple registry credentials.

Add a new `.global.imagePullSecrets` section or just `.imagePullSecrets` on the top in the `values.yaml`?

**Review by fantapsody — APPROVED** [review]

**Comment by fantapsody** [comment]
TODO: update the image version of operators.

**Review by MarvinCai — APPROVED** [review]

**Comment by Huanli-Meng** [comment]
Double confirmed with @ericsyh & @maxsxu , there is no need to add doc for this PR. therefore, remove doc-required label and add no-need-doc label.

**Pull request merged**
