### PR TITLE
Fix Datadog annotation for Autodiscovery.

### PR DESCRIPTION
**Pull request by MarvinCai**
Update container name to the name used by operator if operator is enabled.

Resolve: https://github.com/streamnative/charts/issues/483

### CODE REVIEW

**Review by sijie — COMMENTED** [review]
@MarvinCai do we need to change the function worker?

**Comment by MarvinCai** [comment]
dedicated function worker is not managed by operator, also currently there's no datadog config for function worker
if we want to add that we can probably have another pr for that.

**Review by sijie — APPROVED** [review]

**Comment by sijie** [comment]
Add `doc-required` label as we might need to document how sn-platform can integrate datadog for metrics autodiscovery.

**Comment by Huanli-Meng** [comment]
The doc is updated. Here is the [PR](https://github.com/streamnative/doc-platform/pull/381). Therefore, remove the doc-required label and add doc-added label.

**Pull request merged**
