### PR TITLE
[BREAK CHANGE]: remove resource cr in sn-platform

### LINKED ISSUE #725: [Private Cloud]: remove resource cr

### PR DESCRIPTION
**Pull request by ericsyh**
Signed-off-by: ericsyh <ericshenyuhao@outlook.com>

*(If this PR fixes a github issue, please add `Fixes #<xyz>`.)*

Fixes #725 

*(or if this PR is one task of a github issue, please add `Master Issue: #<xyz>` to link to the master issue.)*

Master Issue: #<xyz>

### Motivation

Since we have released https://github.com/streamnative/pulsar-resources-operator, we should remove resources cr in `sn-platform`

### Modifications

Remove resource cr 

### Verifying this change

- [x] Make sure that the change passes the CI checks.

*(Please pick either of the following options)*

This change is a trivial rework / code cleanup without any test coverage.

*(or)*

This change is already covered by existing tests, such as *(please describe tests)*.

*(or)*

This change added tests and can be verified as follows:

*(example:)*
  - *Added integration tests for end-to-end deployment with large payloads (10MB)*
  - *Extended integration test for recovery after broker failure*

### Documentation

Check the box below.

Need to update docs? 

- [ ] `doc-required` 
  
  (If you need help on updating docs, create a doc issue)
  
- [x] `no-need-doc` 
  
  (Please explain why)
  
- [ ] `doc` 
  
  (If this PR contains doc changes)

### CODE REVIEW

**Review by maxsxu — APPROVED** [review]
The chart linter reports some trailing-spaces error

**Review by FushuWang — APPROVED** [review]

**Comment by maxsxu** [comment]
> The chart linter reports some trailing-spaces error

@ericsyh This linter error has been fixed by https://github.com/streamnative/charts/pull/899. Need to rebase the master branch to fix the CI error.

**Review by maxsxu — APPROVED** [review]

**Comment by sde-melo** [comment]
Where are we supposed to declare entities now?

**Comment by ericsyh** [comment]
> Where are we supposed to declare entities now?

Not to declare, we separated entities as a single operator as https://github.com/streamnative/pulsar-resources-operator

**Comment by sde-melo** [comment]
I have deployed it but it does not create entities if I am not mistaken.

**Comment by ericsyh** [comment]
> I have deployed it but it does not create entities if I am not mistaken.

Oh, I mean, we removed: 
1. Resources CRD in the Pulsar Operator which is separated into the resource operator. 
2. Entities templates in the `sn-platform` chart, should follow the https://github.com/streamnative/pulsar-resources-operator/tree/main/docs to create Pulsar Resources CR. 

After this change, we won't provide a helm chart for entities cause the chart is not easy for users to integrate or make some customize.

**Comment by sde-melo** [comment]
Ok, thanks for your answer

**Pull request merged**
