### PR TITLE
[sn-platform] Support resources limits for init containers

### LINKED ISSUE #810: [sn-platform] Support resources limits for init containers
### Motivation

The `initContainers` of the following components lacks a resources limits:

- zookeeper-cluster
- zookeeper-backup sts
- broker-cluster
- console job
- console sts
- detector deployment
- function-worker sts

### PR DESCRIPTION
**Pull request by maxsxu**
Fixes #810 

### Motivation

Support resources limits for init containers in sn-platform according to [Resource Management for Pods and Containers
](https://kubernetes.io/docs/concepts/configuration/manage-resources-containers/)

It should be noted that the resources strategy is different from regular containers as [quoted](https://kubernetes.io/docs/concepts/workloads/pods/init-containers/#resources) below:
>The highest of any particular resource request or limit defined on all init containers is the effective init request/limit. If any resource has no resource limit specified this is considered as the highest limit.

### Modifications

Added `<component>.initContainers.resources.limits`

```
<component>:
  initContainers:
    resources:
      limits:
        cpu: "0.1"
        memory: 250MBi
```

### Verifying this change

- [x] Make sure that the change passes the CI checks.

This change added tests and can be verified as follows:

Test values.yaml

```
zookeeper:
  customTools:
    restore:
      enable: true
  initContainers:
    resources:
      limits:
        cpu: "0.1"
        memory: "250MBi"

broker:
  customTools:
    restore:
      enable: true
  initContainers:
    resources:
      limits:
        cpu: "0.1"
        memory: "250MBi"

streamnative_console:
  initContainers:
    resources:
      limits:
        cpu: "0.1"
        memory: "250MBi"

pulsar_detector:
  initContainers:
    resources:
      limits:
        cpu: "0.1"
        memory: "250MBi"

functions:
  useDedicatedRunner: true
  initContainers:
    resources:
      limits:
        cpu: "0.1"
        memory: "250MBi"
```

### Documentation

- [ ] `doc-required` 
  
  (If you need help on updating docs, create a doc issue)
  
- [x] `no-need-doc` 
  
  (Please explain why)
  
- [ ] `doc` 
  
  (If this PR contains doc changes)

### CODE REVIEW

**Review by MarvinCai — APPROVED** [review]
lgtm

**Review by fantapsody — COMMENTED** [review]
How about just using resources for these components? It seems using different resources for init containers won't help too much and will add complexity:

> Given the ordering and execution for init containers, the following rules for resource usage apply:
> 
> The highest of any particular resource request or limit defined on all init containers is the effective init request/limit. If any resource has no resource limit specified this is considered as the highest limit.
> The Pod's effective request/limit for a resource is the higher of:
> the sum of all app containers request/limit for a resource
> the effective init request/limit for a resource
> Scheduling is done based on effective requests/limits, which means init containers can reserve resources for initialization that are not used during the life of the Pod.
> The QoS (quality of service) tier of the Pod's effective QoS tier is the QoS tier for init containers and app containers alike.
> Quota and limits are applied based on the effective Pod request and limit.
> 
> Pod level control groups (cgroups) are based on the effective Pod request and limit, the same as the scheduler

https://kubernetes.io/docs/concepts/workloads/pods/init-containers/#resources

**Comment by maxsxu** [comment]
> How about just using resources for these components? It seems using different resources for init containers won't help too much and will add complexity:
> 
> > Given the ordering and execution for init containers, the following rules for resource usage apply:
> > The highest of any particular resource request or limit defined on all init containers is the effective init request/limit. If any resource has no resource limit specified this is considered as the highest limit.
> > The Pod's effective request/limit for a resource is the higher of:
> > the sum of all app containers request/limit for a resource
> > the effective init request/limit for a resource
> > Scheduling is done based on effective requests/limits, which means init containers can reserve resources for initialization that are not used during the life of the Pod.
> > The QoS (quality of service) tier of the Pod's effective QoS tier is the QoS tier for init containers and app containers alike.
> > Quota and limits are applied based on the effective Pod request and limit.
> > Pod level control groups (cgroups) are based on the effective Pod request and limit, the same as the scheduler
> 
> https://kubernetes.io/docs/concepts/workloads/pods/init-containers/#resources

That definitely makes big sense. Updated.

Just FYI, I made a conclusion about the resources strategy:
```
podResources=max(initResources, appResources)

initResources=max(resources of initContainers)

appResources=sum(resources of containers)
```

**Review by fantapsody — APPROVED** [review]

**Comment by fantapsody** [comment]
> ```
> podResources=max(initResources, appResources)
> 
> initResources=max(resources of initContainers)
> 
> appResources=sum(resources of containers)
> ```

Very nice!

**Comment by yuweisung** [comment]
I think we need resources.{limits,request}.{cpu,memory} too.  
V's openshift env still error out during broker init.



Warning FailedCreate 5m11s job-controller Error creating: pods "pulsartest-sn-platform-broker-metadata-init-g6bdn" is forbidden: failed quota: tmtrflaavzbcvmb-y-vz-npapp-gwgv-quota: must specify limits.cpu,limits.memory,requests.cpu,requests.memory
  Warning FailedCreate 5m1s job-controller Error creating: pods "pulsartest-sn-platform-broker-metadata-init-pjgtj" is forbidden: failed quota: tmtrflaavzbcvmb-y-vz-npapp-gwgv-quota: must specify limits.cpu,limits.memory,requests.cpu,requests.memory
  Warning FailedCreate 4m41s job-controller Error creating: pods "pulsartest-sn-platform-broker-metadata-init-tpkgf" is forbidden: failed quota: tmtrflaavzbcvmb-y-vz-npapp-gwgv-quota: must specify limits.cpu,limits.memory,requests.cpu,requests.memory
  Warning FailedCreate 4m1s job-controller Error creating: pods "pulsartest-sn-platform-broker-metadata-init-cp8ww" is forbidden: failed quota: tmtrflaavzbcvmb-y-vz-npapp-gwgv-quota: must specify limits.cpu,limits.memory,requests.cpu,requests.memory
  Warning FailedCreate 2m40s job-controller Error creating: pods "pulsartest-sn-platform-broker-metadata-init-775b2" is forbidden: failed quota: tmtrflaavzbcvmb-y-vz-npapp-gwgv-quota: must specify limits.cpu,limits.memory,requests.cpu,requests.memory
  Warning FailedCreate 0s job-controller Error creating: pods "pulsartest-sn-platform-broker-metadata-init-d8r7x" is forbidden: failed quota: tmtrflaavzbcvmb-y-vz-npapp-gwgv-quota: must specify limits.cpu,limits.memory,requests.cpu,requests.memory

**Pull request merged**
