### PR TITLE
[sn-platform] Support customizating operator managed resources

### PR DESCRIPTION
**Pull request by fantapsody**
### Motivation

This PR upgrades operators to v0.13.0 and supports setting the `customization` field on custom resources.

### Modifications

- upgrade operators to v0.13.0
- update CRDs
- add `customization` fields

### Verifying this change

- [ ] Make sure that the change passes the CI checks.

*(Please pick either of the following options)*

This change is a trivial rework / code cleanup without any test coverage.

*(or)*

This change is already covered by existing tests, such as *(please describe tests)*.

*(or)*

This change added tests and can be verified as follows:

*(example:)*
  - *Added integration tests for end-to-end deployment with large payloads (10MB)*
  - *Extended integration test for recovery after broker failure*

### Documentation

Check the box below.

Need to update docs? 

- [x] `doc-required` 
  
  (If you need help on updating docs, create a doc issue)
  
- [ ] `no-need-doc` 
  
  (Please explain why)
  
- [ ] `doc` 
  
  (If this PR contains doc changes)

### CODE REVIEW

**Review by urfreespace — APPROVED** [review]

**Review by MarvinCai — APPROVED** [review]
I think we need some doc to let customer know how to use this customize feature, or add some example in value file

**Review by maxsxu — COMMENTED** [review]
I think we should also add `<component>.customization` field to the `values.yaml` file.

**Comment by fantapsody** [comment]
> I think we should also add `<component>.customization` field to the `values.yaml` file.

Let's keep it an internal one at the moment. We can add the documents and manifest examples once we figured out the best ways to let customers use it.

**Comment by ericsyh** [comment]
@fantapsody Is this PR ok to merge?

**Comment by Huanli-Meng** [comment]
> > I think we should also add `<component>.customization` field to the `values.yaml` file.
> 
> Let's keep it an internal one at the moment. We can add the documents and manifest examples once we figured out the best ways to let customers use it.

@fantapsody will this config now can public to our users?

**Comment by fantapsody** [comment]
> @fantapsody will this config now can public to our users?
I think we can hold this for a while.

**Pull request merged**
